version: '3.4'

services:
  mongodb:
    image: mongo:latest
  
  apis:
    build: apis
    image: data-civilizer-api-demo:0.1
    volumes:
        - $PWD/app_storage:/app/storage
    environment:
      - PORT=8089
    ports:
      - "8089:8089"
  
  studio:
    build: studio
    image: data-civilizer-studio-demo:0.1
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/dcstudio
      - WEB_SERVER_PORT=5000
      - SOCKET_SERVER_ENDPOINT=ws://localhost:5002
      - SOCKET_SERVER_PORT=5005
      - API_SERVER_URL=http://apis:8089
    ports:
      - "5000:5000"
      - "5002:5002"
      - "5005:5005"
    depends_on:
      - mongodb
      - apis