version: '3.4'
services:
  grecord_service:
    build: grecord_service
    image: grecord_service:0.1
    volumes:
      - $PWD/app_storage:/app/storage
#    ports:
#      - "8888:8888"
  apis:
    build: apis
    volumes:
        - $PWD/app_storage:/app/storage
    environment:
      - PORT=8089
    image: data-civilizer-api:0.1
    depends_on:
      - grecord_service
  mongodb:
    image: mongo:latest
  studio:
    build: studio
    image: data-civilizer-studio:0.1
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/dcstudio
      - WEB_SERVER_PORT=5000
      - SOCKET_SERVER_ENDPOINT=ws://localhost:5002
      - SOCKET_SERVER_PORT=5005
      - API_SERVER_URL=http://apis:8089
    ports:
      - "5000:5000"
      - "5002:5002"
      - "5005:5005"
      - "8888:8888"
    depends_on:
      - mongodb
      - apis
#  aurum:
#    build: aurum-datadiscovery
#    image: aurum-discovery:0.1


